@echo off
rem Generated by JetBrains Toolbox 1.22.10774 at 2021-11-20T11:30:49.193201

set waitarg=
set ideargs=

:next
set "passwait="
if "%~1"=="--wait" set passwait=1
if "%~1"=="-w" set passwait=1
if defined passwait (set waitarg=/wait)
if not "%~1"=="" (
  if defined passwait (set "ideargs=%ideargs%--wait ") else (set "ideargs=%ideargs%%1 ")
  shift
  goto next
)

start "" %waitarg% C:\Users\rezzmk\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5457.46\bin\idea64.exe %ideargs%